#!/usr/bin/env bash

IMAGES_DIR=/opt/pocker/images

printf "%-35s %-12s %-12s %-15s %-10s\n" \
  "REPOSITORY" "TAG" "IMAGE ID" "CREATED" "SIZE"

printf "%-35s %-12s %-12s %-15s %-10s\n" \
  "----------" "---" "--------" "-------" "----"

declare -A SEEN

now=$(date +%s)

for img in "$IMAGES_DIR"/*; do
  [ -d "$img" ] || continue
  [ -f "$img/index.json" ] || continue

  base=$(basename "$img")

  if [[ "$base" == *"_"* ]]; then
    repo="${base%%_*}"
    tag="${base#*_}"
  else
    repo="$base"
    tag="latest"
  fi

  manifest_digest=$(jq -r '.manifests[0].digest // empty' "$img/index.json")
  [ -n "$manifest_digest" ] || continue

  key="$repo:$tag:$manifest_digest"
  [ -n "${SEEN[$key]}" ] && continue
  SEEN[$key]=1

  image_id=$(echo "$manifest_digest" | cut -d: -f2 | cut -c1-12)

  pulled_epoch=$(stat -c %Y "$img")
  diff=$((now - pulled_epoch))

  if [ $diff -lt 3600 ]; then
    created="$((diff/60)) minutes ago"
  elif [ $diff -lt 86400 ]; then
    created="$((diff/3600)) hours ago"
  else
    created="$((diff/86400)) days ago"
  fi

  size=$(du -sh "$img" | awk '{print $1}')

  printf "%-35s %-12s %-12s %-15s %-10s\n" \
    "$repo" "$tag" "$image_id" "$created" "$size"
done
